//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2023-09-28 09:16:35
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失
//     作者：Harbour CTS
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dapper.Contrib.Extensions;

namespace CNet.Model.Main
{	
   
   [Table("File_Upload")]
    public partial class File_Upload
    {

	   /// <summary>
     	/// 
     	/// </summary>
		[Key]
		public int Id { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public string FileName { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public string FileUrl { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public DateTime CreateTime { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public string CreateUser { get; set; }

		/// <summary>
     	/// 来源ID
     	/// </summary>
		public string SourceID { get; set; }

		/// <summary>
     	/// 来源类型
     	/// </summary>
		public string SourceType { get; set; }

		/// <summary>
     	/// 1 管理端后台 2 外部APP 3内部APP
     	/// </summary>
		public int? AppType { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public string Reamrk { get; set; }

		   
    }
}

