//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2019-10-08 14:27:10
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失
//     作者：Harbour CTS
// </auto-generated>
//------------------------------------------------------------------------------

using CNet.Model;

namespace CNet.DAL
{	
	public partial class Pub_RoleFunctionDAL:BaseDataDapperContrib<Pub_RoleFunction>
    { 
		
    }
}

      
