//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2019-10-08 14:27:10
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失
//     作者：Harbour CTS
// </auto-generated>
//------------------------------------------------------------------------------

using CNet.Model;
using System;
using System.Collections.Generic;

namespace CNet.DAL
{
    public partial class Pub_DepartmentDAL : BaseDataDapperContrib<Pub_Department>
    {
        public List<V_PubDept_Parent> SearchChildDept(string code = "D000001")
        {
            return DapperHelperFactory.GetInstance().Query<V_PubDept_Parent>("p_SearchChildDept",new { deptCodeIn =code}, commandType: System.Data.CommandType.StoredProcedure);
        }
    }
}

      
