//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2022-04-26 12:20:04
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失
//     作者：Harbour CTS
// </auto-generated>
//------------------------------------------------------------------------------


using CNet.Model;
using CNet.DAL;

namespace CNet.BLL
{	
	public partial class Pub_UserBLL:BaseServiceDapperContrib<Model.Pub_User>
    {
     

    }
}

