//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2023-08-12 16:57:56
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失
//     作者：Harbour CTS
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dapper.Contrib.Extensions;

namespace CNet.Main.Model
{	
   
   [Table("Pub_Role")]
    public partial class Pub_Role
    {

	   /// <summary>
     	/// 
     	/// </summary>
		[Key]
		public int Id { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public string RoleCode { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public string RoleName { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public string Remark { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public bool? StopFlag { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public string Crid { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public DateTime Crdt { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public string Lmid { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public DateTime Lmdt { get; set; }

		   
    }
}

