//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2023-10-28 22:16:06
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失
//     作者：Harbour CTS
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dapper.Contrib.Extensions;

namespace CNet.Main.Model
{	
   
   [Table("Wiki_Main")]
    public partial class Wiki_Main
    {

	   /// <summary>
     	/// 
     	/// </summary>
		[Key]
		public int Id { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public string SortCode { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public string Title { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public string Keyword { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public string FilePath { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public string IconPath { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public int? ReadCount { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public DateTime? CreateTime { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public string CreateUser { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public DateTime? EditTime { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public string EditUser { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public bool? StopFlag { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public string Remark { get; set; }

		   
    }
}

