//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2023-04-01 12:31:04
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失
//     作者：Harbour CTS
// </auto-generated>
//------------------------------------------------------------------------------

using CNet.Main.Model;

namespace CNet.Main.DAL
{	
	public partial class Pub_DepartmentDAL:RepositoryMain<Pub_Department>
    { 
		
    }
}

      
