//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2023-10-28 22:02:59
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失
//     作者：Harbour CTS
// </auto-generated>
//------------------------------------------------------------------------------


using CNet.Model.Main;
using CNet.DAL.Main;

namespace CNet.BLL.Main
{	
	public partial class Wiki_SortBLL:ServiceMain<Wiki_Sort>
    {
     

    }
}

